### ISSUE TITLE
Presedence -> Precedence

### ISSUE THREAD

**Issue by ArsenShnurkov** [patrickhuber/Pliant#65]
prooflink
https://en.wikipedia.org/wiki/Precedence

locations:
<a href="https://github.com/patrickhuber/Pliant/blob/dd03ca2942d999a8eb2e30a51b3ccf8d3c70602d/libraries/Pliant/Pliant.csproj#L65">1</a>, <a href="https://github.com/patrickhuber/Pliant/blob/dd03ca2942d999a8eb2e30a51b3ccf8d3c70602d/libraries/Pliant/Forest/SelectHigherPresedenceDisambiguationAlgorithm.cs#L9">2</a>

**Comment by patrickhuber** [comment]
Thanks for the heads up, have it fixed local and will push up to dev branch soon
