### ISSUE TITLE
Req: Pliant input language description

### ISSUE THREAD

**Issue by ArsenShnurkov** [patrickhuber/Pliant#76]
To write grammars for Pliant, one need to know how to do that (I mean when grammar is loaded from text file). In particular, how to write regular expressions, how to define strings, characters by code and so on. Also, some examples will be nice to have (Morse code parser from UTF-8 file (&bull;&bull;&bull;&#x2043;&#x2043;&#x2043;&bull;&bull;&bull;) , or something like that).

**Comment by patrickhuber** [comment]
This was addressed in pull request #92
