### ISSUE TITLE
Compatibility with red-green trees of roslyn

### ISSUE THREAD

**Issue by ArsenShnurkov** [patrickhuber/Pliant#79]
Does it worth to implement this algorithm on top of roslyn syntax trees?

https://stackoverflow.com/questions/25963328/how-does-the-release-version-of-roslyn-implement-immutable-trees

documentation of roslyn:
https://roslyn.codeplex.com/wikipage?title=Overview&referringTitle=Documentation

**Comment by patrickhuber** [comment]
What is the goal? Do you want to update the underlying Source and have the ast update our the other way around?

**Comment by ArsenShnurkov** [comment]
I want both - the ability to edit underlying source through AST (for tools), and dynamic syntax highlighting (for editors).

**Comment by ArsenShnurkov** [comment]
Roslyn contains unsafe code, so i dismiss the idea
