### ISSUE TITLE
the symbol 'λ' is not described

### ISSUE THREAD

**Issue by ArsenShnurkov** [patrickhuber/Pliant#88]
1) on the page 
https://github.com/patrickhuber/Pliant/blob/master/documentation/regex.md
the symbol 'λ' is not described. Is it '&epsilon;' ?

2) also there is no hyperlinks to descriptions of '_NotCloseBracketCharacter_', '_NotMetaCharacter_', '_EscapeSequence_'.

3) on the page
https://github.com/patrickhuber/Pliant/blob/master/documentation/morse-code-grammar.md
there is no examples of:
   - optional comments (single line and multiline if they differs)
   - defining the start symbol (s?)

4) on the page 
https://github.com/patrickhuber/Pliant/blob/master/documentation/grammars.md
(which is very, very good), it will be nice to have a note about national symbols support (is it possible to write grammar in national language with unicode or not)

5) there should be an explaination on what is default extension for grammar files, and how to parse such grammars from "hello parser" example (may be "examples" directory needs to be added). How to print a forest? How to disambiguate in typical cases? Right now there are textual descriptions, not examples of code.

6) It is also desirable to create directory "grammars" with examples of other grammars (like EBNF, ABNF, SQL, XML, and others)

**Comment by patrickhuber** [comment]
Good points. I'll split off a branch for this work and we can continue the discussion as part of the pull request.

**Comment by patrickhuber** [comment]
I've addressed these in the latest merge to master
